kiwiproject/registry-aware-jersey-client

- pom.xml
* dropwizard-config-providers -> 0.5.0
* kiwi -> 0.14.0
* service-discovery-client -> 0.6.0
* kiwi-test -> 0.9.0
> Update kiwi project dependencies

- src/main/java/org/kiwiproject/jersey/client/ServiceIdentifier.java
- src/test/java/org/kiwiproject/jersey/client/ServiceIdentifierTest.java
> Add copyOf method to provide a straight copy of ServiceIdentifier

- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClient.java
- src/main/java/org/kiwiproject/jersey/client/exception/MissingServiceRuntimeException.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientTest.java
> Move MissingServiceRuntimeException to a top level class

- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClientBuilder.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientBuilderTest.java
> Add default NoopHostnameVerifier if hostnameVerifier not set

- src/main/java/org/kiwiproject/jersey/client/ClientBuilder.java
- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClient.java
- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClientBuilder.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientBuilderTest.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientTest.java
> Add ability to supply headers to RegistryAwareClient

- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClient.java
> Add more documentation to the targetForService calls

- src/main/java/org/kiwiproject/jersey/client/dropwizard/DropwizardManagedClientBuilder.java
- src/test/java/org/kiwiproject/jersey/client/dropwizard/DropwizardManagedClientBuilderTest.java
> Add default JerseyClientConfiguration creator methods

- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClient.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientTest.java
* Add RegistryAwareClient#targetForService(String serviceName,
PortType portType)
Closes #40
> Add overloaded targetForService method taking a PortType

- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClient.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientBuilderTest.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientTest.java
- src/test/java/org/kiwiproject/jersey/client/dropwizard/DropwizardClientsTest.java
- src/test/java/org/kiwiproject/registry/NoOpRegistryClient.java
> Require non-null Client and RegistryClient in RegistryAwareClient

- pom.xml
- src/test/java/org/kiwiproject/registry/NoOpRegistryClient.java
* Add new RegistryClient method to NoOpRegistryClient
> Bump service-discovery-client from 0.9.0 to 0.10.0

- pom.xml
> Bump service-discovery-client from 0.10.0 to 0.11.0

- src/main/java/org/kiwiproject/jersey/client/ServiceIdentifier.java
- src/test/java/org/kiwiproject/jersey/client/ServiceIdentifierTest.java
* Add getConnectTimeoutAsIntMillis() to ServiceIdentifier
* Add getReadTimeoutAsIntMillis() to ServiceIdentifier
* Validate the connect and read timeouts in the constructor. They must
be convertible to an int (per CONNECT_TIMEOUT and READ_TIMEOUT in
Jersey's ClientProperties class). This will fail-fast if someone
tries to configure a timeout that is too large (and we don't expect
this to ever happen, but it could...)
* Add tests for new methods and the new construction validation logic
* Also add tests to verify whatever version of Jersey we're using still
has the requirement for timeouts to be convertible to an integer. This
is basically a canary that will die (fail the tests) if Jersey ever
changes its implementation.
Closes #88
> Add adapter methods in ServiceIdentifier to get timeouts as int millis

- src/main/java/org/kiwiproject/jersey/client/ServiceIdentifier.java
- src/test/java/org/kiwiproject/jersey/client/ServiceIdentifierTest.java
* Add ServiceIdentifier.of(String serviceName)
* Add ServiceIdentifier.of(String serviceName, PortType connector)
Closes #93
> Add factory methods to ServiceIdentifier

- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClient.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientTest.java
> Make RegistryAwareClient implement AutoCloseable

- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClient.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientTest.java
> Add isClosed to RegistryAwareClient

- pom.xml
* Bump kiwi from 4.5.0 to 4.5.2
* Bump dropwizard-config-providers from 2.3.3 to 2.3.4
> Bump kiwi and dropwizard-config-providers

- src/main/java/org/kiwiproject/jersey/client/ClientBuilder.java
- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClientBuilder.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientBuilderTest.java
> Add connect/readTimeout methods to ClientBuilder with Duration arg

- src/main/java/org/kiwiproject/jersey/client/ClientBuilder.java
- src/main/java/org/kiwiproject/jersey/client/RegistryAwareClientBuilder.java
- src/test/java/org/kiwiproject/jersey/client/RegistryAwareClientBuilderTest.java
- src/test/java/org/kiwiproject/jersey/client/util/JerseyTestHelpers.java
> Add methods to ClientBuilder to set properties and register components

- pom.xml
Add dependencies that we directly use in imports.
Closes #388
> Update direct dependencies

- src/test/java/org/kiwiproject/jersey/client/dropwizard/DropwizardManagedClientBuilderTest.java
- Make clientExtension field static and rename to CLIENT_EXTENSION
- Before each test, reset the MetricRegistry associated with the Environment of the
CLIENT_EXTENSION. This avoids IllegalArgumentException thrown when registering
a metric with the same name.
These changes mean the fake Dropwizard application is only started once per test 
class (including Nested classes), instead of once per individual test. Overall, when running
only DropwizardManagedClientBuilderTest in IntelliJ, the time dropped from over 3 seconds
to less than one second on my M2 MacBook Pro. The difference is less pronounced when
running the entire test suite, presumably due to some initialization or "warmup" somewhere.
> Refactor DropwizardManagedClientBuilderTest to make it faster
